name: 自动更新 RSS

on:
  schedule:
   - cron: '0,30 * * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  update_rss:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 安装依赖
        run: |
          pip install requests beautifulsoup4

      - name: 运行批量生成脚本
        run: |
          python generate_all_feeds.py

      - name: 提交并推送更新
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add u3c3_feed_*.xml
          git diff --quiet && git diff --cached --quiet || git commit -m "Auto update RSS feeds"
          git push origin main
